// ============== ADD USERS
CREATE TABLE customers (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	emailAddress VARCHAR(50) NOT NULL,
	password VARCHAR(150) NOT NULL,
	address VARCHAR(150) NOT NULL,
	city VARCHAR(150) NOT NULL,
	postcode VARCHAR(9) NOT NULL
)

// ============== ADD SHOPS
CREATE TABLE stores (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	storeName VARCHAR(50) NOT NULL,
	logoImage VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL,
	city VARCHAR(150) NOT NULL,
	postcode VARCHAR(150) NOT NULL	
)

// ============== ADD PRODUCTS with foreign key
CREATE TABLE products (
  id INTEGER NOT NULL PRIMARY KEY
      GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  storeId INTEGER NOT NULL,
  productName VARCHAR(100) NOT NULL,
  productImage VARCHAR(50) NOT NULL,
  quantity INTEGER NOT NULL,
  price DOUBLE NOT NULL,
  FOREIGN KEY(storeId) REFERENCES stores(id)
)