/* ========================== ADD USERS*/
CREATE TABLE customers (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	emailAddress VARCHAR(50) NOT NULL,
	password VARCHAR(150) NOT NULL,
	address VARCHAR(150) NOT NULL,
	city VARCHAR(150) NOT NULL,
	postcode VARCHAR(9) NOT NULL
)

/* ========================== ADD SHOPS*/
CREATE TABLE stores (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	storeName VARCHAR(50) NOT NULL,
	logoImage VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL,
	city VARCHAR(150) NOT NULL,
	postcode VARCHAR(150) NOT NULL	
)

/* ========================== ADD PRODUCTS -- WITH FOREIGN KEY*/
CREATE TABLE products (
  id INTEGER NOT NULL PRIMARY KEY
      GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  storeId INTEGER NOT NULL,
  productName VARCHAR(100) NOT NULL,
  imageName VARCHAR(200) NOT NULL,
  quantity INTEGER NOT NULL,
  price DOUBLE NOT NULL,
  FOREIGN KEY(storeId) REFERENCES stores(id)
)

/* ========================== ADD CART TABLE -- WITH FOREIGN KEYS */
CREATE TABLE cart (
  id INTEGER NOT NULL PRIMARY KEY
      GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  customerId INTEGER NOT NULL,
  productId INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  subTotal double,
  FOREIGN KEY(customerId) REFERENCES customers(id),
  FOREIGN KEY(productId) REFERENCES products(id)
)

/* ========================== DEVELOPER MESSAGES TABLE */
CREATE TABLE developerMessages (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	adminName VARCHAR(50) NOT NULL,
	message VARCHAR(150) NOT NULL
)

/* ========================== ADMIN MESSAGES TABLE */
CREATE TABLE adminMessages (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	developer VARCHAR(50) NOT NULL,
	message VARCHAR(150) NOT NULL
)

/* ========================== IMAGES TABLE */
CREATE TABLE images (
	id INTEGER NOT NULL PRIMARY KEY
		GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
	name VARCHAR(50) NOT NULL,
	fileName VARCHAR(150) NOT NULL
)